// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 费用信息。不同 provider 的费用模型差异较大，因此只固定 total/currency。
 */
export type CostUsage = { total: number | null, currency: string | null, };
