// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TokenUsage } from "./TokenUsage";

/**
 * 按模型拆分的用量汇总。
 */
export type ModelUsage = { model: string, tokens: TokenUsage, cost: number, };
