// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CostUsage } from "./CostUsage";
import type { ModelUsage } from "./ModelUsage";
import type { TokenUsage } from "./TokenUsage";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * 会话更新请求。用于更新模型、token、费用等聚合数据，
 * 以及按模型拆分的增量用量（daemon 侧按模型累加）。
 */
export type SessionUpdateRequest = { session_id: string, model: string | null, tokens: TokenUsage | null, cost: CostUsage | null, model_usage: Array<ModelUsage> | null, metadata: JsonValue | null, };
