// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CostUsage } from "./CostUsage";
import type { ModelUsage } from "./ModelUsage";
import type { TokenUsage } from "./TokenUsage";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * 会话更新请求。可携带累计 usage 快照和活动状态。
 */
export type SessionUpdateRequest = { session_id: string, session_instance_id: string | null, code_agent: string, model: string | null, tokens: TokenUsage | null, cost: CostUsage | null, model_usage: Array<ModelUsage> | null,
/**
 * `Some(false)` 表示在 `active_at` 时刻结束当前活动片段。
 */
active: boolean | null, active_at: string | null, metadata: JsonValue | null, };
