// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 会话心跳请求。由扩展周期性发送，表示该 session 仍然活跃。
 */
export type SessionHeartbeatRequest = { session_id: string, };
