// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * 会话更新请求。用于更新模型、metadata 等非 usage 信息。
 */
export type SessionUpdateRequest = { session_id: string, code_agent: string, model: string | null, metadata: JsonValue | null, };
