// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CostUsage } from "./CostUsage";
import type { TokenUsage } from "./TokenUsage";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * 会话开始请求。
 */
export type SessionStartRequest = { session_id: string | null, code_agent: string, project_dir: string, model: string | null, tokens: TokenUsage | null, cost: CostUsage | null, started_at: string | null, metadata: JsonValue | null, };
