// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CostUsage } from "./CostUsage";
import type { ModelUsage } from "./ModelUsage";
import type { TokenUsage } from "./TokenUsage";
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * 会话结束请求。按模型拆分的增量数据在结束时也会发送
 * 最后一轮，确保 daemon 侧数据完整。
 */
export type SessionEndRequest = { session_id: string, ended_at: string | null, tokens: TokenUsage | null, cost: CostUsage | null, model_usage: Array<ModelUsage> | null, metadata: JsonValue | null, };
