// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * 会话开始请求。
 */
export type SessionStartRequest = { session_id: string, code_agent: string, project_dir: string, model: string | null, started_at: string | null, metadata: JsonValue | null, };
