// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * token 使用量。字段全部可选/可累加，方便不同 agent 只上报自己能拿到的数据。
 */
export type TokenUsage = { input: number | null, output: number | null, cache_read: number | null, cache_write: number | null, total: number | null, };
